name: "driver_config"
description: "Runs a wind plant and electrolyzer with simple optimization"

general:
  folder_output: wind_plant_run

driver:
  optimization:
    flag: True
    tol: 0.1
    max_iter: 100
    solver: COBYLA
    rhobeg: 500.
    debug_print: True

design_variables:
  electrolyzer:
    electrolyzer_size_mw:
      flag: True
      lower: 200
      upper: 1800.
      units: MW

constraints:
  electrolyzer:
    total_hydrogen_produced:
      flag: True
      lower: 60500000.
      units: kg/year

objective:
  name: financials_group_1.LCOH
